"""Deterministic water-quality data used by the four-pond demo."""

DEMO_SENSOR_SPECS = (
    {"metric": "AMMONIA", "slug": "ammonia", "name": "氨氮", "unit": "mg/L"},
    {"metric": "NITRITE", "slug": "nitrite", "name": "亚硝酸根离子", "unit": "mg/L"},
    {"metric": "TURBIDITY", "slug": "turbidity", "name": "浊度", "unit": "NTU"},
    {"metric": "CHLOROPHYLL", "slug": "chlorophyll", "name": "叶绿素", "unit": "ug/L"},
    {"metric": "DO", "slug": "do", "name": "溶解氧", "unit": "mg/L"},
    {"metric": "PH", "slug": "ph", "name": "pH", "unit": "pH"},
    {"metric": "TEMPERATURE", "slug": "temperature", "name": "水温", "unit": "°C"},
)

DEMO_SENSOR_BY_METRIC = {item["metric"]: item for item in DEMO_SENSOR_SPECS}

DEMO_WATER_SERIES = {
    "B-01": {
        "AMMONIA": (0.12, 0.13, 0.14, 0.13, 0.15, 0.16, 0.15, 0.14, 0.13),
        "NITRITE": (0.03, 0.03, 0.04, 0.04, 0.05, 0.04, 0.04, 0.03, 0.04),
        "TURBIDITY": (16.0, 17.2, 18.4, 19.0, 18.1, 17.6, 18.8, 19.4, 18.6),
        "CHLOROPHYLL": (8.5, 8.9, 9.2, 9.7, 10.2, 9.8, 9.4, 9.1, 9.3),
        "DO": (5.7, 5.6, 5.5, 5.3, 5.2, 5.4, 5.6, 5.5, 5.7),
        "PH": (7.42, 7.45, 7.48, 7.52, 7.55, 7.51, 7.47, 7.46, 7.49),
        "TEMPERATURE": (25.4, 25.6, 25.8, 26.0, 26.1, 25.9, 25.7, 25.6, 25.8),
    },
    "B-02": {
        "AMMONIA": (0.20, 0.21, 0.22, 0.24, 0.26, 0.25, 0.24, 0.23, 0.25),
        "NITRITE": (0.06, 0.07, 0.08, 0.09, 0.10, 0.09, 0.08, 0.09, 0.10),
        "TURBIDITY": (24.0, 25.3, 27.1, 29.4, 31.0, 29.8, 28.6, 30.2, 30.8),
        "CHLOROPHYLL": (12.0, 12.4, 12.9, 13.5, 14.0, 13.8, 13.4, 13.7, 14.1),
        "DO": (5.0, 4.9, 4.7, 4.6, 4.5, 4.4, 4.5, 4.3, 4.2),
        "PH": (7.72, 7.76, 7.81, 7.86, 7.91, 7.88, 7.84, 7.87, 7.90),
        "TEMPERATURE": (26.3, 26.5, 26.8, 27.0, 27.2, 27.1, 26.9, 26.8, 27.0),
    },
    "B-03": {
        "AMMONIA": (0.10, 0.10, 0.11, 0.12, 0.11, 0.10, 0.09, 0.10, 0.11),
        "NITRITE": (0.02, 0.02, 0.03, 0.03, 0.03, 0.02, 0.02, 0.02, 0.03),
        "TURBIDITY": (12.0, 12.6, 13.1, 13.8, 13.4, 12.9, 12.5, 12.8, 13.0),
        "CHLOROPHYLL": (7.0, 7.2, 7.5, 7.8, 7.6, 7.3, 7.1, 7.4, 7.5),
        "DO": (6.0, 6.1, 6.3, 6.4, 6.2, 6.5, 6.4, 6.6, 6.5),
        "PH": (7.30, 7.33, 7.36, 7.40, 7.38, 7.35, 7.32, 7.34, 7.37),
        "TEMPERATURE": (24.8, 25.0, 25.2, 25.4, 25.3, 25.1, 24.9, 25.0, 25.2),
    },
    "B-04": {
        "AMMONIA": (0.16, 0.17, 0.18, 0.19, 0.18, 0.17, 0.18, 0.19, 0.18),
        "NITRITE": (0.04, 0.04, 0.05, 0.05, 0.06, 0.05, 0.05, 0.04, 0.05),
        "TURBIDITY": (18.0, 18.8, 19.6, 20.5, 21.0, 20.2, 19.8, 20.1, 20.4),
        "CHLOROPHYLL": (14.5, 14.9, 15.3, 15.8, 16.1, 15.7, 15.4, 15.6, 15.9),
        "DO": (5.3, 5.2, 5.0, 4.8, 4.9, 5.1, 4.9, 4.8, 4.9),
        "PH": (7.92, 7.96, 8.01, 8.06, 8.10, 8.07, 8.03, 8.05, 8.08),
        "TEMPERATURE": (27.2, 27.4, 27.6, 27.9, 28.1, 28.0, 27.8, 27.7, 27.9),
    },
}

# These are deliberately non-threshold signals. They are joined by the Agent
# with weather, camera observations and the disease reference set before an
# action is proposed.
DEMO_WEATHER = {
    "B-01": {
        "condition": "晴热",
        "temperature_c": 33.6,
        "wind_speed_mps": 0.8,
        "wind_direction": "东南",
        "humidity_pct": 71,
        "rain_probability_pct": 8,
        "pressure_hpa": 1004.2,
        "forecast": "未来 2 小时晴热少风，水面交换偏弱",
    },
    "B-02": {
        "condition": "多云",
        "temperature_c": 28.1,
        "wind_speed_mps": 2.4,
        "wind_direction": "东",
        "humidity_pct": 78,
        "rain_probability_pct": 35,
        "pressure_hpa": 1008.6,
        "forecast": "未来 6 小时无明显降雨，适合采样复核",
    },
    "B-03": {
        "condition": "阴",
        "temperature_c": 26.4,
        "wind_speed_mps": 1.7,
        "wind_direction": "东北",
        "humidity_pct": 82,
        "rain_probability_pct": 48,
        "pressure_hpa": 1007.8,
        "forecast": "未来一小时云量增加，建议暂停下一轮投喂并观察摄食反应",
    },
    "B-04": {
        "condition": "雷雨前",
        "temperature_c": 29.2,
        "wind_speed_mps": 5.8,
        "wind_direction": "西南",
        "humidity_pct": 89,
        "rain_probability_pct": 86,
        "pressure_hpa": 997.4,
        "forecast": "未来 45 分钟有强降雨和阵风，建议保护进排水设施",
    },
}

DEMO_DISEASE_KNOWLEDGE = (
    {
        "id": "kb-columnaris",
        "name": "细菌性鳃病 / 柱状病",
        "species": "加州鲈、草鱼",
        "signs": "鳃丝肿胀、黏液增多、体表灰白斑，摄食下降",
        "visual_cues": ["鳃丝发白", "鳃部黏液", "体表灰白斑", "摄食下降"],
        "recommended_actions": ["隔离疑似个体", "采集鳃丝和体表样本镜检", "暂缓跨池转运"],
        "severity": "HIGH",
    },
    {
        "id": "kb-ich",
        "name": "小瓜虫病",
        "species": "淡水鱼",
        "signs": "体表或鳍条散布白点，摩擦池壁，呼吸频率升高",
        "visual_cues": ["针尖状白点", "摩擦池壁", "鳍条收拢", "呼吸急促"],
        "recommended_actions": ["隔离并复核镜检", "降低应激", "由养殖专家确认处理方案"],
        "severity": "HIGH",
    },
    {
        "id": "kb-epistylis",
        "name": "车轮虫 / 钟形虫疑似感染",
        "species": "鱼苗及育成鱼",
        "signs": "体表絮状附着、游动迟缓、局部鳃盖开合异常",
        "visual_cues": ["絮状附着物", "游动迟缓", "鳃盖开合异常"],
        "recommended_actions": ["采样送检", "检查有机负荷和底部残饵", "人工确认后再处理"],
        "severity": "MEDIUM",
    },
)

DEMO_CAMERA_OBSERVATIONS = (
    {
        "id": "obs-surface-b01-floating-head",
        "camera_id": "camera-surface-b01",
        "pond_id": "B-01",
        "camera_role": "SURFACE",
        "observation_type": "FLOATING_HEAD_GATHERING",
        "status": "READY",
        "summary": "水面北侧连续出现 12 尾鱼短时浮头并聚集在进水口附近，未见明显投喂诱因",
        "labels": ["浮头聚集", "进水口聚集", "短时重复出现"],
        "confidence": 0.91,
    },
    {
        "id": "obs-underwater-b02-disease",
        "camera_id": "camera-underwater-b02",
        "pond_id": "B-02",
        "camera_role": "UNDERWATER",
        "observation_type": "DISEASE_SUSPECT",
        "status": "READY",
        "summary": "水下连续帧发现 3 尾鱼体表针尖状白点、鳍条收拢和擦壁动作，疑似寄生虫性病害",
        "labels": ["针尖白点", "擦壁", "鳍条收拢", "呼吸急促"],
        "confidence": 0.86,
    },
    {
        "id": "obs-surface-b03-feeding",
        "camera_id": "camera-surface-b03",
        "pond_id": "B-03",
        "camera_role": "SURFACE",
        "observation_type": "WEAK_FEEDING_RESPONSE",
        "status": "READY",
        "summary": "投喂窗口内水面响应延迟，残饵在投喂区停留超过上一周期，未观察到抢食扩散",
        "labels": ["摄食响应弱", "残饵滞留", "响应延迟"],
        "confidence": 0.88,
    },
    {
        "id": "obs-surface-b04-weather-front",
        "camera_id": "camera-surface-b04",
        "pond_id": "B-04",
        "camera_role": "SURFACE",
        "observation_type": "DEBRIS_AND_WAVE_RISK",
        "status": "READY",
        "summary": "水面漂浮物增多、浪高快速上升，进水口附近出现树叶和泡沫带，疑似天气过程前兆",
        "labels": ["漂浮物增多", "浪高上升", "进水口风险"],
        "confidence": 0.83,
    },
)

DEMO_ANALYSIS_CASES = (
    {
        "id": "case-floating-head-weather",
        "sequence": 1,
        "title": "浮头聚集 × 晴热少风",
        "category": "水面视觉 + 天气",
        "pond_id": "B-01",
        "trigger": "水面摄像头识别重复浮头，天气 Agent 发现高温少风",
        "description": "不能只看溶氧阈值，要结合浮头空间分布、天气和设备影子状态判断是否先行增氧。",
        "evidence_refs": ["obs-surface-b01-floating-head", "weather-B-01"],
        "expected_path": "视觉证据 → 天气交叉验证 → 增氧机开启 → MQTT 确认 → 复核",
        "expected_device_id": "aerator-b01-1",
        "expected_target_state": "on",
        "expected_result": "低风险时自动开启增氧机",
    },
    {
        "id": "case-underwater-disease",
        "sequence": 2,
        "title": "水下白点 × 病害知识匹配",
        "category": "水下视觉 + 病害知识库",
        "pond_id": "B-02",
        "trigger": "水下摄像头发现白点、擦壁和鳍条收拢",
        "description": "视觉模型只给疑似信号，Agent 需要检索病害知识库并决定采样、隔离或人工确认，禁止自行投药。",
        "evidence_refs": ["obs-underwater-b02-disease", "kb-ich"],
        "expected_path": "水下视觉 → 知识库检索 → 风险分级 → 采样/隔离人工任务",
        "expected_device_id": "",
        "expected_target_state": "",
        "expected_result": "创建病害复核人工任务，不直接投药",
    },
    {
        "id": "case-weak-feeding-response",
        "sequence": 3,
        "title": "摄食响应弱 × 残饵滞留",
        "category": "水面视觉 + 投喂设备",
        "pond_id": "B-03",
        "trigger": "投喂窗口视觉响应变慢且残饵滞留",
        "description": "Agent 结合摄食行为和天气预报，判断是否暂停下一轮投喂，避免继续增加水体有机负荷。",
        "evidence_refs": ["obs-surface-b03-feeding", "weather-B-03"],
        "expected_path": "摄食行为分析 → 天气上下文 → 暂停投喂机 → MQTT 确认",
        "expected_device_id": "feeder-b03-1",
        "expected_target_state": "off",
        "expected_result": "自动暂停下一轮投喂，等待人工复核",
    },
    {
        "id": "case-weather-front-protection",
        "sequence": 4,
        "title": "强降雨前兆 × 进排水保护",
        "category": "水面视觉 + 天气预警",
        "pond_id": "B-04",
        "trigger": "漂浮物和浪高变化与雷雨前天气联合出现",
        "description": "Agent 评估天气过程对进排水设施的风险，优先提出关闭进水阀的受控建议，并保留人工审批边界。",
        "evidence_refs": ["obs-surface-b04-weather-front", "weather-B-04"],
        "expected_path": "水面风险识别 → 天气预报核验 → 阀门保护建议 → 审批/人工执行",
        "expected_device_id": "valve-b04-1",
        "expected_target_state": "off",
        "expected_result": "形成中风险阀门保护建议，需人工审批",
    },
)
